### ISSUE TITLE
Add option to hide Settings window on startup

### ISSUE THREAD

**Issue by ben-nason** [CVMEventi/Countdown#25]
Hello CVMEventi,

Your Countdown app is great! But I'd like to be able to run it in a window on one Mac and use the HTTP interface for control it from another Mac. I can do this now, but on the Mac that's running Countdown the Settings window is always present, if I close the settings window it closes the app. Which makes some sense for local control, if you have the clock view on one display and the settings/controls on another, but I just want to control it remotely and only see the settings view when I want to change the settings from the menu bar like most apps. Yes, I can minimize the Settings window to the Dock, but then the user can accidentally unminimized it, I don't want that to be possible.

Regards,

Ben

**Comment by cipi1965** [comment]
Hello, i can think on putting it on tray and hide the window instead of closing app. Could it work for you?

**Comment by ben-nason** [comment]
Hi Matteo,

Thanks for following up! Yes, if the app had a way to hide the Settings window in the menubar or tray that would work. Ideally there would be an option for it to be hidden by default, so that if the computer restarts, and is configured to automatically open countdown on login, it would just present the timer window.

Regards,

Ben

**Comment by cipi1965** [comment]
Hi,
in 0.0.37 is it possible to close the window without closing the app. In the upcoming 0.0.38 it will be possible to start with window hidden :)
